use std::error::Error;
pub async fn evt_loop(//mut send: tokio::sync::mpsc::Receiver<Msg>,
    //recv: tokio::sync::mpsc::Sender<Msg>,
    //topic: gossipsub::IdentTopic,
) -> Result<(), Box<dyn Error>> {
    Ok(())
}
